### ISSUE TITLE
Add `/etc/apparmor.d/tunables/alias` to ensure proper path resolution for apparmor profiles in live mode

### ISSUE THREAD

**Issue by mckinney-subgraph** [subgraph/subgraph_desktop_stretch#1]
Need to add these aliases:

```
alias / -> /lib/live/mount/overlay/,
alias / -> /lib/live/mount/rootfs/filesystem.squashfs/,
alias / -> /rw/,
```

**Comment by intrigeri** [comment]
This is what we do in Tails, but it brings a few new problems: https://tails.boum.org/contribute/design/application_isolation/#index4h2

We manually solved some of them (mostly profiles failing to load due to overlapping rules) by patching AppArmor policy: see `apparmor-*` in https://git-tails.immerda.ch/tails/tree/config/chroot_local-patches/.
